### ISSUE TITLE
Template List.xml (RSS feed) throws an exception

### ISSUE THREAD

**Issue by ryanklarhoelter** [georgringer/news#243]
Fluid tries to resolve the HTML elements `<atom:link>` and `<content:encoded>`.

Error message:

> Fluid parse error in template News_action_list_d21febc792464a481b182233a10d925372d6a97f, line 21 at character 1. Error: The ViewHelper "<atom:link>" could not be resolved. Based on your spelling, the system would load the class "http:\\www.w3.org\2005\Atom\ViewHelpers\LinkViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <atom:link href="{f:uri.page(pageType: 9818) -> f:format.htmlentities()}" rel="self" type="application/rss+xml" />

News version: 5.3.2.

TYPO3 version: 8.6.0-dev

**Comment by NamelessCoder** [comment]
Putting `{namespace atom}` (sic) in the template file should solve this. It adds the ns alias as ignored alias and tags will be output including original xmlns prefix.

**Comment by georgringer** [comment]
@NamelessCoder sorry it doesn't help :(

**Comment by macayer** [comment]
Any news on that ? I have the same error, but on line 1 
Uncaught TYPO3 Exception
#1407060572: Fluid parse error in template News_action_List_48371fbb8bb65ab6719d06de0e0445c9689bf351, line 1  [...]

**Comment by NamelessCoder** [comment]
Solved with https://review.typo3.org/#/c/51711, pending release - to fix it now locally, do `composer update typo3fluid/fluid`. The semantic versioning scheme allows Fluid 2.3.1 to be installed on 8.4 and above.

**Comment by ryanklarhoelter** [comment]
Seems to work mostly. Unfortunately `{f:uri.page(pageType: 9818) -> f:format.htmlentities()}` within `<atom:link>` does not work:

![auswahl_002](https://cloud.githubusercontent.com/assets/6748888/23264528/ea9bedb8-f9e1-11e6-9299-32497c61b5c4.png)

**Comment by macayer** [comment]
@NamelessCoder  Yes, it works ! Thank you

**Comment by christian-fries** [comment]
Resolved with #374

**Comment by taniamorales** [comment]
There is still a problem with the namespaces but it only happens after the first load of the xml page. 
i.e. news v6.1.1 . Default templates. TYPO3 v8.7.8. (also previous and 8.7.9-dev).

When you load the rss.xml page the first time after clearing the caches there is no error, if you load it again then you get:

" PHP Warning: in_array() expects parameter 2 to be array, null given in /Users/tania/Sites/Bitbucket/typo3-tilburg-tilburgnl-upgrade87/typo3_src/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperResolver.php line 92 "

Only by removing the namespaces and tags for atom and content there is no error anymore.
Another thing I noticed is that the namespaces for fluid and news are shown on the generated rss which we don't want so I had to use:

{namespace f=TYPO3\CMS\Fluid\ViewHelpers}
{namespace n=GeorgRinger\News\ViewHelpers}

**Comment by gautamsinh** [comment]
Yes , I have also face same issue as @taniamorales  

After reload it gives error like: 
" PHP Warning: in_array() expects parameter 2 to be array, null given in .../typo3_src/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperResolver.php line 92 "

**Comment by 0bserver** [comment]
Since TYPO3 gets the hickups trying to parse namespaces and tags as Fluid-related when they are really not I tried to circumvent that parsing step using the following code in List.xml (note that EXT:vhs must be installed for this example to work, but you can try your luck with f:cObject):

```html
{namespace f=TYPO3\CMS\Fluid\ViewHelpers}
{namespace n=GeorgRinger\News\ViewHelpers}
{namespace v=FluidTYPO3\Vhs\ViewHelpers}
{v:variable.set(name: 'xmlns', value: 'xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom"')}
{v:variable.set(name: 'atom', value: 'atom')}
{v:variable.set(name: 'content', value: 'content')}
<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" {xmlns -> f:format.htmlentitiesDecode()}>
```
and below
```html
<{atom -> f:format.crop(maxCharacters: 40)}:link …
<{content -> f:format.crop(maxCharacters: 40)}:encoded> …
```
You can try it without `f:format.crop(maxCharacters: 40)` but I added it to make sure all strings had to be processed by a ViewHelper and would not be erroneously interpreted as ViewHelpers themselves. The `f:format.htmlentitiesDecode()` is definitely necessary because of the quotation marks.

I hope this workaround will help you (and me) to bridge the time until a proper solution exists.

**Comment by georgringer** [comment]
can't reproduce with 8+9 which are the upcoming supported versions, therefore I am closing it
