### ISSUE TITLE
Content element preview causes BE exception with gridelements

### ISSUE THREAD

**Issue by kboss** [georgringer/news#385]
TYPO3 7.6.20 with news 6.1.0-dev and gridelements 7.1.0 (current 7-0 branch)

With activated ``records.contentElementPreview`` editing a news item containing a gridelement throws an exception:

```
Call to undefined method TYPO3\CMS\Backend\Controller\EditDocumentController::contentIsNotLockedForEditors()

Error thrown in file
/html/typo3_v7/typo3conf/ext/gridelements/Classes/Hooks/DrawItem.php in line 454.
```

Full trace can be provided.

**Comment by georgringer** [comment]
but the error is thrown in gridelements .. I guess it should be fixed there?!

**Comment by kboss** [comment]
Thanks for the hint. I should have come up myself with linking the exception to gridelements. :open_mouth:

I've created an issue there: https://forge.typo3.org/issues/81938

**Comment by Geddo** [comment]
sorry for bumping but this error also occurs with flux grids.
https://github.com/georgringer/news/commit/9ac8056a5d4eb6f9addfef81f9118835e7d5922f does not fix this tho as  flux grids can have any CType name they want :-/

**Comment by Gitsko** [comment]
I have the same Problem with flux, is there any solution ?
